meta_product_name: "The Women Box"
meta_title: "The Women Box - Lo esenial para el periodo"
meta_description: "Recibe mes a mes todo lo que necesitas para el periodo en la puerta de tu casa"
meta_image: "banner_suscripcion3.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@LopezDaniel10"   # required for Twitter Cards
