meta_product_name: "The Women Box"
meta_title: "The Women Box - Lo esencial para el periodo"
meta_description: "Lo que necesitas para el periodo: toallas o tampones, pañitos húmedos, protectores, productos de belleza, snacks y sorpresas. Todo a la puerta de tu casa."
meta_image: "meta.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@LopezDaniel10"   # required for Twitter Cards
