meta_product_name: "The Women Box"
meta_title: "The Women Box - Lo esenial para el periodo"
meta_description: "Te entregamos mes a mes todo lo que necesitas para recibir el periodo con la mejor actitud"
meta_image: "meta.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@LopezDaniel10"   # required for Twitter Cards
